language: php
php:
- 7.1
services:
  - redis-server
matrix:
  allow_failures:
  - php: hhvm
before_script:
- cp .env.travis .env
- composer install --no-interaction
- mkdir -p build/logs
script:
- vendor/bin/phpunit --coverage-clover build/logs/clover.xml
after_success:
- travis_retry php vendor/bin/coveralls
env:
  global:
  - secure: kwM/LytpXrLtGJruAtBtCI5IDzw0SSKPVYOOIS4LOkS44XqBE/nAldbMffmfXtGPp0G5Vd1dg1nYiJwccfeMIA54j7YyibJTTbDC9LiVG7uWv/EOehTFIlFP2IyYueYPwTvzOZdFOXpzT5GWOv6HzZrRrBaa/v5W0unkisxKpzX/r5PXdYyAtF9aDYDMIx4QmPkEuWUQSYhC3hryp5utBdyFpP+Jc/HsJdV8sg+8MHlwrrXiBupYmwWAHLoLFfQ+ypThV1VrWTJ6GR4kq5gruh83L5Wgi3SsieIQ1/9J+R8dwLx0XBiXT2bZ1piZuROZKnbHWOxtk6rObyCj5l5AWCnvfg1Agd4RtWFk18C6KkPro5kfKYdxQWTwHC8LXItrDgA+WKN5UuOhCx6zycCCJrPuoTT2pJdWyVRRC1OLLkMW5s6VROjVGpWUrtm/VYVOd2F6HNFZmQDfZtvc6Z503glXWgxNWLR3dWJYDklmPv7bj259z+bjPL0evw6p3KU8aNIPDqMF+ViPEVXyW2y75yXXh26BzELVC4uu4rD+42WdD4RSM9kJY9kTERsFgI3MvwcK3c7/JByxqvs15d+HOxAOF/QZ7t2apCVkNEoSI0EcUp8mPP8M1bDgg6pFqEIjBjwoNHBC2s9Ib0LxcHE0wxcQXd+nzv5vX0iK5+q8i+Q=
  - secure: ZH6NiI4DsSyuh51G9Hq+bqqBT0cJEQyZ4pX1grFhRxeJEgLbx8t8jSljJVh4y6BaGPoQ04OFajQpgoz1/qkb3pFJgp7Ng2zP80a//yJCBZVYp3CfsDZsfod+i7rNvmE22yFBxpYwybORrSAHgqVdLxUq4iKGjQ1YfWKJpTfsKds58RtUWpTllpBhbAFfhbuJ9tCdvSrvnyxpBYdJ4N/r8oWVa0/N9bWoPMeaAEmAPQUobxTjw1v3C5OKoItI9c9A0ys8g1Q5bge5vWAyS6Fj5vf1WozG5Q9zsXPrvOUVozNpQWraahXtCM1FKnbumAe0v+aQX/uj0vpAZCzjx5vZBvXNkF8HSo0grJOI3AGuHgypY7go32eOesbDp5gSWngPYBbrV7I5kyeuMKyKnMy30KmXa5UZaD6tOfCLgOeCiRP6fBuIC3B6waR7qRa7nwo5QlGE8+ejzYylElSyychjphYNUVzLs/nRnSR7BVb2FTC3BDMiSwMnquCVn85LHNV7lnN4sveKZRMUHw5d1NvjJhc/LWqiqcePaB4dEwjju9IeL3PQHOx/vCJF6WehiLmvzr6AAc80ctZ83fYJP07PvJtOHWp1g5WhBji/0czk3y6L6MlKqxoJ/slHm4X5XxgnxJpci5hdeiwOFb7NIGKxDUvXwGi1H2mhUyNdzJCYJyM=
