language: php
php:
- 7.1
matrix:
  allow_failures:
  - php: hhvm
before_script:
- cp .env.travis .env
- composer install --no-interaction
- mkdir -p build/logs
script:
- vendor/bin/phpunit --coverage-clover build/logs/clover.xml
after_success:
- travis_retry php vendor/bin/coveralls
env:
  secure: ROWNFtdArMFx7fz/6Y57iIm3vQDv8r6jtlmz8k1EP72X/p/cHHuYgZdrJ/h80cFhsIq4kBU/1Q6Ys1uWufM4d2QawVjK9XKkIzku2ltlXk4twz6HrRHNDeNA2r3P0FTU9zW3Z9k4+vmOoCupGUcyNTKBDJ/BMy8I4dQvxIA4E0xBHHAsav/U51IW8GB3AVFmvtOmfQRddyOAMKL0c7OsXOoUwgsmjxjv2ivXGMRAUyWGzf4+hcCSJz4P12pm18lP726BjRhC8xeyHxvVNkKsEVImJt3ANte24DBeqHReynBoB0PuGhe1xa8P/E1KyLcyO6Gp/jCA64ElPcfknSz1oSb/mrnnVLonF9gju7WfHzj+arW3OJiOpkJGj3l1j8ahk01LcbalvRsusA+zk0ZdGVvJW/PnYpkS/IS1SP0BsRsjyhGMiar24xoi7p5F99lluL559pxGAv8UPAtkh0Yqo71Avd+PX+vSu3mdH3kY6R9AkwNeaSeNY7O822suzTJi8WAJLX5IBABM3z48X1jT0cZtRqM8SKl0MoTuFPjPp7XphQDEtMrkJGrZEG2khx3XiRA4YBqTHLn868shSPp2LaTFL61dVQoy0uHXRTkB26YPXC0Zvn9V73X3rUDidweuvZjl/maXV3uy0bE1SYT6g2kk82c6SlFwMSKukb38TiE=
