language: php
php:
- 7.1
matrix:
  allow_failures:
  - php: hhvm
before_script:
- cp .env.travis .env
- composer install --no-interaction
- mkdir -p build/logs
script:
- vendor/bin/phpunit --coverage-clover build/logs/clover.xml
after_success:
- travis_retry php vendor/bin/coveralls
env:
  secure: Ic5NlzpuQWVPZHmu1wd+AC6VGWJYnWYp6sSnvbrqO/ycOixyDHFsNoxT2aTUXTc2PnQlTWzY0JL30dCETCJBQvNhYYXK8sp9yl4XkeQUTd8oVO3e5zVfsKi+2ZR2a/C/baFt5XXALF2sxOoe0adPz+U07VuT7kxnEl8tq5qMYHisTdehaym4d2Xm2Z2lMCrt7yJbu8XP9AHdvl0I4+dbylkcJHGPn3d/8z+8BAQ5M9vFM80f2KcHs28TQ6uQ6quNqlIFBFGK7mKEUTtFDGdRfmn+aYBA0dvTFy+j+BqfXHbfR/o1GI/sXBcn54wtQ0PpMrGoiHEXcOFP9mbl6CzC/JgiUG2DE5nLcnwcv5uecfo6cnz1UEBoChsh21PYvvPLYqWAPu4gQUmSj34leuLjEMmMX1lsMB5vg6ZWKTXN5y389dRQgMHxbkXI4AKjfaH8d2y1mUltW9wPqKx2JMCu4HjuiGWzubV+PbH/tRZMElPDywOVr5KWgRIj8W3df1sDpWVAYlBVeJwMssMRJvpnk7dF4KJUX0yGK5RiELIFO4sOUEeFdocLkFMn7KZblya9/S3+ytDnpfUgrHwN9wyS0OeqGI98Db6tujJ6iSW52CbGuV5nXrhXuBBrLqJ7r2Z8M4Sls+J0yveJy2SwBJfg9navrojDg+jtAJwKoMVdc8w=
  secure: AAAvUW9C+lxi80AEHpTh+e8NZShIXMl6OrHyKwFRt6b0ZxXEDJxier6PMFQs1Gkv1N9KUvZZH4KzBlbADTq3/yl8bqYqaNZLPhuCuCFcUjDDNFhDHeYV/lshOwka62GbAxNuqJoQIFwEqSAl0zPYxlu2Iw9NczvXblrvw6r9UZBF30nHPA9lHBpyZPzPJsJCyRcEJYYxlWQ3AyLJTD1Wjess6PTkykdA/Tqa2SviFL9AXFmTRAT7fNldNUaPwPgTWqXJsmc+lATiQFO+TRfpUC06l7Og2pLVmNndTMEcehnnSmjfuTG+56aAY1IS12Anr2/QjwGWMFrN8HVYsC4I5Hz0lU6MPM8oEKkJa36ALYaAbqTC0JZdQLFVedWEqPNaNl3Qn4gpKEJ5Uv7Vgle5QEqmwCfYJwKNUS4aUdUskx5T1oMObvuADgCs6A/ETPfZ08ev82IeHP7fUsh3+DCNLfFq9ZbukoSuNi+J9p+2+2f7at/EGUDDfrcBgKWgy0cRwDE+NVkyCNkfd/ynK/whzsV49+saiAmyjP16lrr/IC6KpNYb7KDVFPh6wVsdkKzkNOvMBHJRxK/3XYG/tT7SWMG8IyvuWnZdycgmmVQWZ/66QQ9BzQGJcNTOVNm2laUlLLA2a9MufHTti1xeMkcuayN/t9EAHDNa9UIDO7Q0//Y=
